//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLogId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string EntityName { get; set; }
        public string EntityKey { get; set; }
        public string ActionName { get; set; }
        public string OldValues { get; set; }
        public string NewValues { get; set; }
        public System.DateTime PerformedAt { get; set; }
        public string Notes { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
