//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanCafe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BanCafe()
        {
            this.DatBans = new HashSet<DatBan>();
            this.HoaDonBans = new HashSet<HoaDonBan>();
        }
    
        public int MaBan { get; set; }
        public string MaCodeBan { get; set; }
        public int MaKhuVuc { get; set; }
        public string TenBan { get; set; }
        public int SucChua { get; set; }
        public string TrangThai { get; set; }
        public string GiaTriQRCode { get; set; }
        public string GhiChu { get; set; }
        public bool ConHoatDong { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public int ViTriX { get; set; }
        public int ViTriY { get; set; }
        public string KieuHinh { get; set; }
        public string MaMau { get; set; }
    
        public virtual KhuVucQuan KhuVucQuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatBan> DatBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBan> HoaDonBans { get; set; }
    }
}
