//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaiDatUngDung
    {
        public string KhoaCaiDat { get; set; }
        public string GiaTriCaiDat { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    }
}
