//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashSession()
        {
            this.SalesOrders = new HashSet<SalesOrder>();
        }
    
        public int CashSessionId { get; set; }
        public string SessionCode { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime OpenedAt { get; set; }
        public Nullable<System.DateTime> ClosedAt { get; set; }
        public decimal OpeningCash { get; set; }
        public Nullable<decimal> ClosingCash { get; set; }
        public decimal ExpectedCash { get; set; }
        public Nullable<decimal> DifferenceAmount { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}
