//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiPhi
    {
        public int MaChiPhi { get; set; }
        public string MaCodeChiPhi { get; set; }
        public int MaDanhMucChiPhi { get; set; }
        public System.DateTime NgayChi { get; set; }
        public decimal SoTien { get; set; }
        public Nullable<int> MaNhanVienChi { get; set; }
        public string MoTa { get; set; }
        public string DuongDanDinhKem { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        public virtual DanhMucChiPhi DanhMucChiPhi { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
