//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietKiemKe
    {
        public int MaChiTietKiemKe { get; set; }
        public int MaPhieuKiemKe { get; set; }
        public int MaNguyenLieu { get; set; }
        public decimal SoLuongHeThong { get; set; }
        public decimal SoLuongThucTe { get; set; }
        public decimal SoLuongChenhLech { get; set; }
        public string LyDo { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual PhieuKiemKe PhieuKiemKe { get; set; }
    }
}
