//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietHoaDonBan()
        {
            this.ChiTietToppingHoaDons = new HashSet<ChiTietToppingHoaDon>();
        }
    
        public int MaChiTietHoaDonBan { get; set; }
        public int MaHoaDonBan { get; set; }
        public int MaBienThe { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public decimal TienGiam { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string TrangThaiMon { get; set; }
        public string YeuCauDacBiet { get; set; }
        public Nullable<int> MaNhanVienPhaChe { get; set; }
        public Nullable<System.DateTime> BatDauLuc { get; set; }
        public Nullable<System.DateTime> HoanThanhLuc { get; set; }
        public string LyDoHuy { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietToppingHoaDon> ChiTietToppingHoaDons { get; set; }
    }
}
