//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuKho
    {
        public int MaChiTietPhieuKho { get; set; }
        public int MaPhieuKho { get; set; }
        public int MaNguyenLieu { get; set; }
        public decimal SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual PhieuKho PhieuKho { get; set; }
    }
}
