//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietCongThuc
    {
        public int MaBienThe { get; set; }
        public int MaNguyenLieu { get; set; }
        public decimal SoLuongCan { get; set; }
        public decimal PhanTramHaoHut { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BienTheSanPham BienTheSanPham { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
