//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietToppingHoaDon
    {
        public int MaChiTietTopping { get; set; }
        public int MaChiTietHoaDonBan { get; set; }
        public int MaTopping { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual ChiTietHoaDonBan ChiTietHoaDonBan { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
