//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPointTransaction
    {
        public int PointTransactionId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public int PointsChanged { get; set; }
        public string Reason { get; set; }
        public Nullable<int> CreatedByEmployeeId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
