//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatBan()
        {
            this.HoaDonBans = new HashSet<HoaDonBan>();
        }
    
        public int MaDatBan { get; set; }
        public string MaPhieuDatBan { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaBan { get; set; }
        public string NguoiLienHe { get; set; }
        public string SoDienThoaiLienHe { get; set; }
        public int SoKhach { get; set; }
        public System.DateTime ThoiGianDat { get; set; }
        public string TrangThai { get; set; }
        public string YeuCauDacBiet { get; set; }
        public Nullable<int> MaNhanVienTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        public virtual BanCafe BanCafe { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBan> HoaDonBans { get; set; }
    }
}
