//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpenseId { get; set; }
        public string ExpenseCode { get; set; }
        public int ExpenseCategoryId { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> PaidByEmployeeId { get; set; }
        public string Description { get; set; }
        public string AttachmentPath { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ExpenseCategory ExpenseCategory { get; set; }
    }
}
