//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDichKho
    {
        public int MaGiaoDichKho { get; set; }
        public int MaNguyenLieu { get; set; }
        public string LoaiGiaoDich { get; set; }
        public string LoaiThamChieu { get; set; }
        public Nullable<int> MaThamChieu { get; set; }
        public decimal SoLuongThayDoi { get; set; }
        public Nullable<decimal> DonGiaVon { get; set; }
        public System.DateTime NgayGiaoDich { get; set; }
        public Nullable<int> MaNhanVienTao { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
