//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDichDiemKhachHang
    {
        public int MaGiaoDichDiem { get; set; }
        public int MaKH { get; set; }
        public Nullable<int> MaHoaDonBan { get; set; }
        public int SoDiemThayDoi { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> MaNhanVienTao { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
