//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDichThanhToan
    {
        public int MaGiaoDichThanhToan { get; set; }
        public int MaHoaDonBan { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public decimal SoTien { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public string SoThamChieu { get; set; }
        public Nullable<int> MaNhanVienNhanTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
