//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnhSanPham
    {
        public int MaHinhAnhSanPham { get; set; }
        public int MaSanPham { get; set; }
        public string DuongDanHinhAnh { get; set; }
        public string MoTaHinh { get; set; }
        public bool LaHinhChinh { get; set; }
        public int ThuTuHienThi { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
