//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonBan()
        {
            this.ChiTietHoaDonBans = new HashSet<ChiTietHoaDonBan>();
            this.GiaoDichDiemKhachHangs = new HashSet<GiaoDichDiemKhachHang>();
            this.GiaoDichThanhToans = new HashSet<GiaoDichThanhToan>();
        }
    
        public int MaHoaDonBan { get; set; }
        public string MaHoaDon { get; set; }
        public Nullable<int> MaBan { get; set; }
        public Nullable<int> MaKH { get; set; }
        public int MaThuNgan { get; set; }
        public Nullable<int> MaDatBan { get; set; }
        public Nullable<int> MaKhuyenMaiApDung { get; set; }
        public string LoaiHoaDon { get; set; }
        public string TrangThaiHoaDon { get; set; }
        public string TrangThaiThanhToan { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public System.DateTime NgayLapHoaDon { get; set; }
        public Nullable<System.DateTime> ThoiGianDong { get; set; }
        public decimal TienHang { get; set; }
        public decimal TienTopping { get; set; }
        public decimal TienGiam { get; set; }
        public decimal TienThue { get; set; }
        public decimal PhiDichVu { get; set; }
        public decimal TongTien { get; set; }
        public decimal TienKhachTra { get; set; }
        public decimal TienThua { get; set; }
        public Nullable<int> SoKhach { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public string TenKhachTam { get; set; }
        public string SoDienThoaiKhachTam { get; set; }
        public string GhiChuHoaDon { get; set; }
        public string KenhNguon { get; set; }
        public string MaMangDi { get; set; }
        public string LyDoHuy { get; set; }
        public Nullable<int> MaNhanVienHuy { get; set; }
        public Nullable<int> MaPhienThu { get; set; }
    
        public virtual BanCafe BanCafe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonBan> ChiTietHoaDonBans { get; set; }
        public virtual DatBan DatBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichDiemKhachHang> GiaoDichDiemKhachHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichThanhToan> GiaoDichThanhToans { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual PhienThu PhienThu { get; set; }
    }
}
