//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTransaction
    {
        public int InventoryTransactionId { get; set; }
        public int IngredientId { get; set; }
        public string TransactionType { get; set; }
        public string ReferenceType { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public decimal QuantityChange { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> CreatedByEmployeeId { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
