//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuVucQuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuVucQuan()
        {
            this.BanCafes = new HashSet<BanCafe>();
        }
    
        public int MaKhuVuc { get; set; }
        public string MaCodeKhuVuc { get; set; }
        public string TenKhuVuc { get; set; }
        public string TenTang { get; set; }
        public string MoTa { get; set; }
        public int ThuTuHienThi { get; set; }
        public bool ConHoatDong { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanCafe> BanCafes { get; set; }
    }
}
