//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemAddonMap
    {
        public int MenuItemId { get; set; }
        public int AddonId { get; set; }
        public Nullable<decimal> ExtraPriceOverride { get; set; }
        public bool IsDefaultAvailable { get; set; }
    
        public virtual Addon Addon { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
