//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemImage
    {
        public int MenuItemImageId { get; set; }
        public int MenuItemId { get; set; }
        public string ImagePath { get; set; }
        public string ImageAlt { get; set; }
        public bool IsPrimary { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
    }
}
