//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItem()
        {
            this.MenuItemAddonMaps = new HashSet<MenuItemAddonMap>();
            this.MenuItemImages = new HashSet<MenuItemImage>();
            this.MenuItemVariants = new HashSet<MenuItemVariant>();
        }
    
        public int MenuItemId { get; set; }
        public string ItemCode { get; set; }
        public int CategoryId { get; set; }
        public string ItemName { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
        public string OriginCountry { get; set; }
        public int PreparationTimeMinutes { get; set; }
        public Nullable<int> Calories { get; set; }
        public string ImagePath { get; set; }
        public bool IsSignature { get; set; }
        public bool IsSeasonal { get; set; }
        public bool IsAvailable { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string DisplayColorHex { get; set; }
        public string SearchKeywords { get; set; }
        public int SortOrder { get; set; }
        public bool IsBestSeller { get; set; }
        public bool IsNewItem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItemAddonMap> MenuItemAddonMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItemImage> MenuItemImages { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItemVariant> MenuItemVariants { get; set; }
    }
}
