//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyQuanCaPheDbEntities1 : DbContext
    {
        public QuanLyQuanCaPheDbEntities1()
            : base("name=QuanLyQuanCaPheDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addon> Addons { get; set; }
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<BanCafe> BanCafes { get; set; }
        public virtual DbSet<BienTheSanPham> BienTheSanPhams { get; set; }
        public virtual DbSet<CafeArea> CafeAreas { get; set; }
        public virtual DbSet<CafeTable> CafeTables { get; set; }
        public virtual DbSet<CaiDatUngDung> CaiDatUngDungs { get; set; }
        public virtual DbSet<CaLam> CaLams { get; set; }
        public virtual DbSet<CashSession> CashSessions { get; set; }
        public virtual DbSet<CustomerLevel> CustomerLevels { get; set; }
        public virtual DbSet<CustomerPointTransaction> CustomerPointTransactions { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<ChiPhi> ChiPhis { get; set; }
        public virtual DbSet<ChiTietCongThuc> ChiTietCongThucs { get; set; }
        public virtual DbSet<ChiTietHoaDonBan> ChiTietHoaDonBans { get; set; }
        public virtual DbSet<ChiTietHoaDonNhap> ChiTietHoaDonNhaps { get; set; }
        public virtual DbSet<ChiTietKiemKe> ChiTietKiemKes { get; set; }
        public virtual DbSet<ChiTietToppingHoaDon> ChiTietToppingHoaDons { get; set; }
        public virtual DbSet<DanhMucChiPhi> DanhMucChiPhis { get; set; }
        public virtual DbSet<DanhMucSanPham> DanhMucSanPhams { get; set; }
        public virtual DbSet<DatBan> DatBans { get; set; }
        public virtual DbSet<DonViTinh> DonViTinhs { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<ExpenseCategory> ExpenseCategories { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<GiaoDichDiemKhachHang> GiaoDichDiemKhachHangs { get; set; }
        public virtual DbSet<GiaoDichKho> GiaoDichKhos { get; set; }
        public virtual DbSet<GiaoDichThanhToan> GiaoDichThanhToans { get; set; }
        public virtual DbSet<HangKhachHang> HangKhachHangs { get; set; }
        public virtual DbSet<HinhAnhSanPham> HinhAnhSanPhams { get; set; }
        public virtual DbSet<HoaDonBan> HoaDonBans { get; set; }
        public virtual DbSet<HoaDonNhap> HoaDonNhaps { get; set; }
        public virtual DbSet<InventoryTransaction> InventoryTransactions { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<KichCoSanPham> KichCoSanPhams { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhuVucQuan> KhuVucQuans { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<MenuItemAddonMap> MenuItemAddonMaps { get; set; }
        public virtual DbSet<MenuItemImage> MenuItemImages { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<MenuItemVariant> MenuItemVariants { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NguyenLieu> NguyenLieus { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhatKyHeThong> NhatKyHeThongs { get; set; }
        public virtual DbSet<PaymentTransaction> PaymentTransactions { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductSize> ProductSizes { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<PurchaseOrderItem> PurchaseOrderItems { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<PhanQuyenVaiTro> PhanQuyenVaiTros { get; set; }
        public virtual DbSet<PhienThu> PhienThus { get; set; }
        public virtual DbSet<PhieuKiemKe> PhieuKiemKes { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<RecipeDetail> RecipeDetails { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SalesOrderItemAddon> SalesOrderItemAddons { get; set; }
        public virtual DbSet<SalesOrderItem> SalesOrderItems { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<SanPhamTopping> SanPhamToppings { get; set; }
        public virtual DbSet<StockTakeItem> StockTakeItems { get; set; }
        public virtual DbSet<StockTakeSession> StockTakeSessions { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<Topping> Toppings { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<VaiTro> VaiTros { get; set; }
        public virtual DbSet<WorkShift> WorkShifts { get; set; }
        public virtual DbSet<vw_BestSellingMenuItems> vw_BestSellingMenuItems { get; set; }
        public virtual DbSet<vw_CashSessionSummary> vw_CashSessionSummary { get; set; }
        public virtual DbSet<vw_DanhMucMenu> vw_DanhMucMenu { get; set; }
        public virtual DbSet<vw_DoanhThuThangTheoDanhMuc> vw_DoanhThuThangTheoDanhMuc { get; set; }
        public virtual DbSet<vw_HangDoiPhaChe> vw_HangDoiPhaChe { get; set; }
        public virtual DbSet<vw_InventoryStatus> vw_InventoryStatus { get; set; }
        public virtual DbSet<vw_KitchenQueue> vw_KitchenQueue { get; set; }
        public virtual DbSet<vw_MenuCatalog> vw_MenuCatalog { get; set; }
        public virtual DbSet<vw_MonthlyRevenueByCategory> vw_MonthlyRevenueByCategory { get; set; }
        public virtual DbSet<vw_PurchaseSummary> vw_PurchaseSummary { get; set; }
        public virtual DbSet<vw_SanPhamBanChay> vw_SanPhamBanChay { get; set; }
        public virtual DbSet<vw_SoDoBan> vw_SoDoBan { get; set; }
        public virtual DbSet<vw_TableMap> vw_TableMap { get; set; }
        public virtual DbSet<vw_TodayDashboard> vw_TodayDashboard { get; set; }
        public virtual DbSet<vw_TongHopNhapHang> vw_TongHopNhapHang { get; set; }
        public virtual DbSet<vw_TongHopPhienThu> vw_TongHopPhienThu { get; set; }
        public virtual DbSet<vw_TongQuanHomNay> vw_TongQuanHomNay { get; set; }
        public virtual DbSet<vw_TrangThaiKho> vw_TrangThaiKho { get; set; }
        public virtual DbSet<ChiTietPhieuKho> ChiTietPhieuKhos { get; set; }
        public virtual DbSet<PhieuKho> PhieuKhos { get; set; }
    }
}
