//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguyenLieu()
        {
            this.ChiTietCongThucs = new HashSet<ChiTietCongThuc>();
            this.ChiTietHoaDonNhaps = new HashSet<ChiTietHoaDonNhap>();
            this.ChiTietKiemKes = new HashSet<ChiTietKiemKe>();
            this.GiaoDichKhos = new HashSet<GiaoDichKho>();
            this.ChiTietPhieuKhos = new HashSet<ChiTietPhieuKho>();
        }
    
        public int MaNguyenLieu { get; set; }
        public string MaCodeNguyenLieu { get; set; }
        public string TenNguyenLieu { get; set; }
        public int MaDonVi { get; set; }
        public string TenDanhMuc { get; set; }
        public decimal SoLuongHienTai { get; set; }
        public decimal SoLuongToiThieu { get; set; }
        public Nullable<decimal> SoLuongToiDa { get; set; }
        public decimal GiaNhapCuoi { get; set; }
        public string ViTriLuuKho { get; set; }
        public int SoNgayCanhBaoHetHan { get; set; }
        public string DuongDanHinhAnh { get; set; }
        public string GhiChu { get; set; }
        public bool ConHoatDong { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietCongThuc> ChiTietCongThucs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonNhap> ChiTietHoaDonNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKiemKe> ChiTietKiemKes { get; set; }
        public virtual DonViTinh DonViTinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDichKho> GiaoDichKhos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuKho> ChiTietPhieuKhos { get; set; }
    }
}
