//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyHeThong
    {
        public int MaNhatKy { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public string TenBang { get; set; }
        public string KhoaDuLieu { get; set; }
        public string TenHanhDong { get; set; }
        public string GiaTriCu { get; set; }
        public string GiaTriMoi { get; set; }
        public System.DateTime ThoiGianThucHien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
