//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string NotificationType { get; set; }
        public string TargetRoleCode { get; set; }
        public Nullable<int> TargetEmployeeId { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
