//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransaction
    {
        public int PaymentTransactionId { get; set; }
        public int SalesOrderId { get; set; }
        public string PaymentMethod { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PaidAt { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> ReceivedByEmployeeId { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
