//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyenVaiTro
    {
        public int MaVaiTro { get; set; }
        public int MaQuyen { get; set; }
        public bool DuocCapQuyen { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual Quyen Quyen { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
