//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKiemKe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuKiemKe()
        {
            this.ChiTietKiemKes = new HashSet<ChiTietKiemKe>();
        }
    
        public int MaPhieuKiemKe { get; set; }
        public string MaCodePhieu { get; set; }
        public string TenPhieu { get; set; }
        public System.DateTime NgayKiemKe { get; set; }
        public string TrangThai { get; set; }
        public int MaNhanVienTao { get; set; }
        public Nullable<int> MaNhanVienDuyet { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKiemKe> ChiTietKiemKes { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
