//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhienThu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhienThu()
        {
            this.HoaDonBans = new HashSet<HoaDonBan>();
        }
    
        public int MaPhienThu { get; set; }
        public string MaCodePhieu { get; set; }
        public int MaNV { get; set; }
        public System.DateTime ThoiGianMo { get; set; }
        public Nullable<System.DateTime> ThoiGianDong { get; set; }
        public decimal TienMatDauCa { get; set; }
        public Nullable<decimal> TienMatCuoiCa { get; set; }
        public decimal TienMatDuKien { get; set; }
        public Nullable<decimal> TienChenhLech { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBan> HoaDonBans { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
