//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuKho()
        {
            this.ChiTietPhieuKhos = new HashSet<ChiTietPhieuKho>();
        }
    
        public int MaPhieuKho { get; set; }
        public string MaCodePhieuKho { get; set; }
        public string LoaiPhieu { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<int> MaNhanVienLap { get; set; }
        public string GhiChu { get; set; }
        public decimal TongTien { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuKho> ChiTietPhieuKhos { get; set; }
    }
}
