//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeDetail
    {
        public int VariantId { get; set; }
        public int IngredientId { get; set; }
        public decimal QuantityRequired { get; set; }
        public decimal WastePercent { get; set; }
        public string Notes { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual MenuItemVariant MenuItemVariant { get; set; }
    }
}
