//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.SalesOrders = new HashSet<SalesOrder>();
        }
    
        public int ReservationId { get; set; }
        public string ReservationCode { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> TableId { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public int GuestCount { get; set; }
        public System.DateTime ReservedAt { get; set; }
        public string Status { get; set; }
        public string SpecialRequest { get; set; }
        public Nullable<int> CreatedByEmployeeId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual CafeTable CafeTable { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}
