//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderItemAddon
    {
        public int SalesOrderItemAddonId { get; set; }
        public int SalesOrderItemId { get; set; }
        public int AddonId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
    
        public virtual Addon Addon { get; set; }
        public virtual SalesOrderItem SalesOrderItem { get; set; }
    }
}
