//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrderItem()
        {
            this.SalesOrderItemAddons = new HashSet<SalesOrderItemAddon>();
        }
    
        public int SalesOrderItemId { get; set; }
        public int SalesOrderId { get; set; }
        public int VariantId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal DiscountAmount { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public string ItemStatus { get; set; }
        public string SpecialRequest { get; set; }
        public Nullable<int> PreparedByEmployeeId { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public string CancelReason { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual MenuItemVariant MenuItemVariant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderItemAddon> SalesOrderItemAddons { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
