//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrder()
        {
            this.CustomerPointTransactions = new HashSet<CustomerPointTransaction>();
            this.PaymentTransactions = new HashSet<PaymentTransaction>();
            this.SalesOrderItems = new HashSet<SalesOrderItem>();
        }
    
        public int SalesOrderId { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int CashierId { get; set; }
        public Nullable<int> ReservationId { get; set; }
        public Nullable<int> AppliedPromotionId { get; set; }
        public string OrderType { get; set; }
        public string OrderStatus { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentMethod { get; set; }
        public System.DateTime OrderedAt { get; set; }
        public Nullable<System.DateTime> ClosedAt { get; set; }
        public decimal MerchandiseAmount { get; set; }
        public decimal AddonAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal ChangeAmount { get; set; }
        public Nullable<int> GuestCount { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string CustomerNameTemp { get; set; }
        public string CustomerPhoneTemp { get; set; }
        public string OrderNote { get; set; }
        public string SourceChannel { get; set; }
        public string TakeAwayCode { get; set; }
        public string CancelReason { get; set; }
        public Nullable<int> CancelledByEmployeeId { get; set; }
        public Nullable<int> CashSessionId { get; set; }
    
        public virtual CafeTable CafeTable { get; set; }
        public virtual CashSession CashSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPointTransaction> CustomerPointTransactions { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual Reservation Reservation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderItem> SalesOrderItems { get; set; }
    }
}
