//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamTopping
    {
        public int MaSanPham { get; set; }
        public int MaTopping { get; set; }
        public Nullable<decimal> GiaThemTuyChinh { get; set; }
        public bool MacDinhCoSan { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
