//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.BienTheSanPhams = new HashSet<BienTheSanPham>();
            this.HinhAnhSanPhams = new HashSet<HinhAnhSanPham>();
            this.SanPhamToppings = new HashSet<SanPhamTopping>();
        }
    
        public int MaSanPham { get; set; }
        public string MaCodeSanPham { get; set; }
        public int MaDanhMuc { get; set; }
        public string TenSanPham { get; set; }
        public string TenNgan { get; set; }
        public string MoTa { get; set; }
        public string XuatXu { get; set; }
        public int ThoiGianPhaChePhut { get; set; }
        public Nullable<int> Calo { get; set; }
        public string DuongDanHinhAnh { get; set; }
        public bool LaMonDacTrung { get; set; }
        public bool LaMonTheoMua { get; set; }
        public bool DangBan { get; set; }
        public bool ConHoatDong { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public string MaMauHienThi { get; set; }
        public string TuKhoaTimKiem { get; set; }
        public int ThuTuSapXep { get; set; }
        public bool BanChay { get; set; }
        public bool MonMoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienTheSanPham> BienTheSanPhams { get; set; }
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnhSanPham> HinhAnhSanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamTopping> SanPhamToppings { get; set; }
    }
}
