//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTakeSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockTakeSession()
        {
            this.StockTakeItems = new HashSet<StockTakeItem>();
        }
    
        public int StockTakeSessionId { get; set; }
        public string SessionCode { get; set; }
        public string SessionName { get; set; }
        public System.DateTime CountDate { get; set; }
        public string Status { get; set; }
        public int CreatedByEmployeeId { get; set; }
        public Nullable<int> ApprovedByEmployeeId { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTakeItem> StockTakeItems { get; set; }
    }
}
