//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTakeItem
    {
        public int StockTakeItemId { get; set; }
        public int StockTakeSessionId { get; set; }
        public int IngredientId { get; set; }
        public decimal ExpectedQuantity { get; set; }
        public decimal ActualQuantity { get; set; }
        public decimal DifferenceQuantity { get; set; }
        public string Reason { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual StockTakeSession StockTakeSession { get; set; }
    }
}
