//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.NhatKyHeThongs = new HashSet<NhatKyHeThong>();
        }
    
        public int MaTaiKhoan { get; set; }
        public int MaNV { get; set; }
        public string TenDangNhap { get; set; }
        public byte[] MatKhauHash { get; set; }
        public byte[] MatKhauSalt { get; set; }
        public bool BatBuocDoiMatKhau { get; set; }
        public int SoLanDangNhapSai { get; set; }
        public bool BiKhoa { get; set; }
        public Nullable<System.DateTime> LanDangNhapCuoi { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhatKyHeThong> NhatKyHeThongs { get; set; }
    }
}
