//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int MaThongBao { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string LoaiThongBao { get; set; }
        public string MaVaiTroNhan { get; set; }
        public Nullable<int> MaNhanVienNhan { get; set; }
        public bool DaDoc { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
