//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BestSellingMenuItems
    {
        public int MenuItemId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ImagePath { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> TotalQuantitySold { get; set; }
        public Nullable<decimal> TotalSalesAmount { get; set; }
        public Nullable<int> OrderCount { get; set; }
        public Nullable<System.DateTime> LastSoldAt { get; set; }
    }
}
