//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CashSessionSummary
    {
        public int CashSessionId { get; set; }
        public string SessionCode { get; set; }
        public int EmployeeId { get; set; }
        public string CashierName { get; set; }
        public System.DateTime OpenedAt { get; set; }
        public Nullable<System.DateTime> ClosedAt { get; set; }
        public decimal OpeningCash { get; set; }
        public Nullable<decimal> ClosingCash { get; set; }
        public decimal ExpectedCash { get; set; }
        public Nullable<decimal> DifferenceAmount { get; set; }
        public string Status { get; set; }
        public Nullable<int> TotalOrders { get; set; }
        public decimal TotalRevenue { get; set; }
        public decimal CashAmount { get; set; }
        public decimal BankTransferAmount { get; set; }
        public decimal CardAmount { get; set; }
        public decimal EWalletAmount { get; set; }
    }
}
