//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DoanhThuThangTheoDanhMuc
    {
        public Nullable<int> RevenueYear { get; set; }
        public Nullable<int> RevenueMonth { get; set; }
        public string MaCodeDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<decimal> MerchandiseRevenue { get; set; }
    }
}
