//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DanhMucMenu
    {
        public string MaCodeDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public string MaCodeSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string DuongDanHinhAnh { get; set; }
        public string MaCodeKichCo { get; set; }
        public string TenKichCo { get; set; }
        public string MaCodeBienThe { get; set; }
        public string VariantDisplayName { get; set; }
        public decimal GiaBan { get; set; }
        public bool DangBan { get; set; }
    }
}
