//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_HangDoiPhaChe
    {
        public int MaChiTietHoaDonBan { get; set; }
        public int MaHoaDonBan { get; set; }
        public string MaHoaDon { get; set; }
        public string LoaiHoaDon { get; set; }
        public string TrangThaiHoaDon { get; set; }
        public System.DateTime NgayLapHoaDon { get; set; }
        public string MaCodeBan { get; set; }
        public string TenBan { get; set; }
        public string TenSanPham { get; set; }
        public string TenKichCo { get; set; }
        public int SoLuong { get; set; }
        public string TrangThaiMon { get; set; }
        public string YeuCauDacBiet { get; set; }
        public Nullable<System.DateTime> BatDauLuc { get; set; }
        public Nullable<System.DateTime> HoanThanhLuc { get; set; }
        public string PreparedByName { get; set; }
        public Nullable<int> WaitingMinutes { get; set; }
    }
}
