//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InventoryStatus
    {
        public string IngredientCode { get; set; }
        public string IngredientName { get; set; }
        public string CategoryName { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public decimal CurrentQuantity { get; set; }
        public decimal MinimumQuantity { get; set; }
        public Nullable<decimal> MaximumQuantity { get; set; }
        public decimal LastUnitCost { get; set; }
        public string StockStatus { get; set; }
    }
}
