//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_KitchenQueue
    {
        public int SalesOrderItemId { get; set; }
        public int SalesOrderId { get; set; }
        public string OrderCode { get; set; }
        public string OrderType { get; set; }
        public string OrderStatus { get; set; }
        public System.DateTime OrderedAt { get; set; }
        public string TableCode { get; set; }
        public string TableName { get; set; }
        public string ItemName { get; set; }
        public string SizeName { get; set; }
        public int Quantity { get; set; }
        public string ItemStatus { get; set; }
        public string SpecialRequest { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public string PreparedByName { get; set; }
        public Nullable<int> WaitingMinutes { get; set; }
    }
}
