//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MenuCatalog
    {
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ImagePath { get; set; }
        public string SizeCode { get; set; }
        public string SizeName { get; set; }
        public string VariantCode { get; set; }
        public string VariantDisplayName { get; set; }
        public decimal SalePrice { get; set; }
        public bool IsAvailable { get; set; }
    }
}
