//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SoDoBan
    {
        public int MaBan { get; set; }
        public string MaCodeBan { get; set; }
        public string TenBan { get; set; }
        public int SucChua { get; set; }
        public string TrangThai { get; set; }
        public int ViTriX { get; set; }
        public int ViTriY { get; set; }
        public string KieuHinh { get; set; }
        public string UiColorHex { get; set; }
        public int MaKhuVuc { get; set; }
        public string MaCodeKhuVuc { get; set; }
        public string TenKhuVuc { get; set; }
        public string TenTang { get; set; }
        public bool ConHoatDong { get; set; }
    }
}
