//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TongHopNhapHang
    {
        public string MaCodeHoaDonNhap { get; set; }
        public System.DateTime NgayLapHoaDon { get; set; }
        public string MaNhaCungCap { get; set; }
        public string TenNhaCungCap { get; set; }
        public string TrangThai { get; set; }
        public string TrangThaiThanhToan { get; set; }
        public decimal TamTinh { get; set; }
        public decimal PhiVanChuyen { get; set; }
        public decimal TienGiam { get; set; }
        public decimal TongTien { get; set; }
    }
}
