//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TongHopPhienThu
    {
        public int MaPhienThu { get; set; }
        public string MaCodePhieu { get; set; }
        public int MaNV { get; set; }
        public string CashierName { get; set; }
        public System.DateTime ThoiGianMo { get; set; }
        public Nullable<System.DateTime> ThoiGianDong { get; set; }
        public decimal TienMatDauCa { get; set; }
        public Nullable<decimal> TienMatCuoiCa { get; set; }
        public decimal TienMatDuKien { get; set; }
        public Nullable<decimal> TienChenhLech { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> TotalOrders { get; set; }
        public decimal TotalRevenue { get; set; }
        public decimal CashAmount { get; set; }
        public decimal BankTransferAmount { get; set; }
        public decimal CardAmount { get; set; }
        public decimal EWalletAmount { get; set; }
    }
}
