//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TableMap
    {
        public int TableId { get; set; }
        public string TableCode { get; set; }
        public string TableName { get; set; }
        public int Capacity { get; set; }
        public string Status { get; set; }
        public int PositionX { get; set; }
        public int PositionY { get; set; }
        public string ShapeType { get; set; }
        public string UiColorHex { get; set; }
        public int AreaId { get; set; }
        public string AreaCode { get; set; }
        public string AreaName { get; set; }
        public string FloorName { get; set; }
        public bool IsActive { get; set; }
    }
}
