//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TodayDashboard
    {
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> TotalOrdersToday { get; set; }
        public Nullable<int> CompletedOrdersToday { get; set; }
        public Nullable<int> CancelledOrdersToday { get; set; }
        public decimal RevenueToday { get; set; }
        public decimal PaidAmountToday { get; set; }
        public Nullable<int> OpenOrders { get; set; }
        public Nullable<int> OccupiedTables { get; set; }
        public Nullable<int> AvailableTables { get; set; }
    }
}
