//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TrangThaiKho
    {
        public string MaCodeNguyenLieu { get; set; }
        public string TenNguyenLieu { get; set; }
        public string TenDanhMuc { get; set; }
        public string MaCodeDonVi { get; set; }
        public string TenDonVi { get; set; }
        public decimal SoLuongHienTai { get; set; }
        public decimal SoLuongToiThieu { get; set; }
        public Nullable<decimal> SoLuongToiDa { get; set; }
        public decimal GiaNhapCuoi { get; set; }
        public string StockStatus { get; set; }
    }
}
