//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCaFe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShift
    {
        public int WorkShiftId { get; set; }
        public string ShiftCode { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string ShiftType { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
